name: 'setup-node'
description: 'setup node'

runs:
  using: 'composite'
  steps:
    - name: Set Node.js version
      shell: bash
      run: echo "NODE_VERSION=$(jq -r .volta.node package.json)" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache node modules
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
      with:
        path: '**/node_modules'
        key: npm-${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/template/package.json') }}
