name: 'setup-node'
description: 'setup node'

runs:
  using: 'composite'
  steps:
    - name: Set Node.js version
      shell: bash
      run: echo "NODE_VERSION=$(jq -r .volta.node package.json)" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache node modules
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: '**/node_modules'
        key: npm-${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/template/package.json') }}
